# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7279330ff8bbdde65afc69becb46c63f950b233d6da3174a4e50e669dc532b50f340f25966756501d980783154fdfcfafa603772dfb7f653bea117f116ea644c

test:
  secret_key_base: aa109eb7897cfe4aadcc611cf8a40aa88b5fbf1b47b8bb49f51a2c240a64243a1d5214f7c6eaa793f697571d5e70932227b1dfd27aa9183797bc60128f77ebeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
